### PyTorch

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import torch

In [2]:
x = np.array([1,2,3])
y = np.array([[1,2,3],[4,5,6]])
z = np.array([[[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]]])

In [3]:
torch.HalfTensor
torch.FloatTensor
torch.DoubleTensor

torch.ShortTensor
torch.IntTensor
torch.LongTensor

torch.CharTensor
torch.ByteTensor

torch.ByteTensor

In [4]:
a = torch.FloatTensor([1,2])
a.shape

torch.Size([2])

In [5]:
b = torch.FloatTensor([[1,2,3],[4,5,6]])
b.shape

torch.Size([2, 3])

In [6]:
# x = torch.FloatTensor(2,3,4)
# x
x = torch.FloatTensor(100)
x

tensor([9.3742e-39, 6.8913e-34, 5.2165e-38, 9.2737e-41, 6.7303e-37, 9.8025e+11,
        2.9577e-27, 9.6429e-39, 6.0256e-38, 6.0266e-38, 6.0268e-38, 2.1128e-39,
        9.2737e-41, 6.7303e-37, 1.5684e+13, 9.3742e-39, 6.8913e-34, 5.2165e-38,
        9.2737e-41, 6.7303e-37, 6.2738e+13, 9.3742e-39, 6.8913e-34, 5.2165e-38,
        9.2737e-41, 6.7303e-37, 2.5096e+14, 9.3742e-39, 6.8913e-34, 5.2165e-38,
        9.2737e-41, 6.7303e-37, 1.0038e+15, 9.3742e-39, 6.8913e-34, 5.2165e-38,
        9.2737e-41, 6.7303e-37, 4.0154e+15, 9.3742e-39, 6.8913e-34, 5.2165e-38,
        9.2737e-41, 6.7303e-37, 1.6062e+16, 9.3742e-39, 6.8913e-34, 5.2165e-38,
        9.2737e-41, 6.7303e-37, 6.4249e+16, 9.3742e-39, 6.8913e-34, 5.2165e-38,
        9.2737e-41, 6.7303e-37, 2.5700e+17, 9.3742e-39, 6.8913e-34, 5.2165e-38,
        9.2737e-41, 6.7303e-37, 1.0280e+18, 9.3742e-39, 6.8913e-34, 5.2165e-38,
        9.2737e-41, 6.7303e-37, 4.1122e+18, 9.3742e-39, 6.8913e-34, 5.2165e-38,
        9.2737e-41, 6.7303e-37, 1.6449e+

In [7]:
z = np.ndarray((2,3,4))
z

array([[[0.2 , 0.2 , 0.6 , 1.  ],
        [0.  , 0.6 , 1.  , 1.  ],
        [0.  , 0.8 , 0.4 , 1.  ]],

       [[1.  , 1.  , 0.6 , 1.  ],
        [0.5 , 0.36, 0.33, 1.  ],
        [1.  , 1.  , 1.  , 1.  ]]])

In [8]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

In [9]:
x = torch.IntTensor(45, 57, 14, 2).zero_()
x

tensor([[[[0, 0],
          [0, 0],
          [0, 0],
          ...,
          [0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0],
          ...,
          [0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0],
          ...,
          [0, 0],
          [0, 0],
          [0, 0]],

         ...,

         [[0, 0],
          [0, 0],
          [0, 0],
          ...,
          [0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0],
          ...,
          [0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0],
          ...,
          [0, 0],
          [0, 0],
          [0, 0]]],


        [[[0, 0],
          [0, 0],
          [0, 0],
          ...,
          [0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0],
          ...,
          [0, 0],
          [0, 0],
   

In [10]:
b = torch.FloatTensor([[1,2,3],[4,5,6]])
b.view(3,2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [11]:
b.view(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [12]:
a = torch.FloatTensor([1.5,3.2,-7])
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [13]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

In [14]:
a = torch.FloatTensor([[100,20,35],[15,163,534],[52,90,66]])
a[0,0]

tensor(100.)

In [15]:
a[0][0]

tensor(100.)

In [16]:
a[0:2,0:2]

tensor([[100.,  20.],
        [ 15., 163.]])

In [17]:
a = torch.FloatTensor([[1,2,3],[10,20,30],[100,200,300]])
b = torch.FloatTensor([[-1,-2,-3],[-10,-20,-30],[-100,-200,-300]])

In [18]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
a.add(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [21]:
a.sub(b)

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [22]:
a * b

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [-1.0000e+04, -4.0000e+04, -9.0000e+04]])

In [23]:
a.mul(b)

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [-1.0000e+04, -4.0000e+04, -9.0000e+04]])

In [24]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])

In [25]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])

In [26]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [27]:
a != b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [28]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [29]:
a[a > b]

tensor([  1.,   2.,   3.,  10.,  20.,  30., 100., 200., 300.])

In [30]:
b[a == b]

tensor([])

In [31]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [32]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [33]:
a.cos()

tensor([[ 0.5403, -0.4161, -0.9900],
        [-0.8391,  0.4081,  0.1543],
        [ 0.8623,  0.4872, -0.0221]])

In [34]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [35]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [36]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [37]:
b -= a
b

tensor([[  -2.,   -4.,   -6.],
        [ -20.,  -40.,  -60.],
        [-200., -400., -600.]])

In [38]:
a.sum()

tensor(666.)

In [39]:
a.mean()

tensor(74.)

In [40]:
a.max()

tensor(300.)

In [41]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

In [42]:
a @ b

tensor([[   -642.,   -1284.,   -1926.],
        [  -6420.,  -12840.,  -19260.],
        [ -64200., -128400., -192600.]])

In [43]:
a = torch.FloatTensor([1,2,3,4,5,6])
b = torch.FloatTensor([-1,-2,-4,-6,-8,-10])

In [44]:
a.dot(b)

tensor(-141.)

In [45]:
a @ b

tensor(-141.)

In [46]:
type(a)

torch.Tensor

In [47]:
a = torch.FloatTensor([[1,2,3],[10,20,30],[100,200,300]])
b = torch.FloatTensor([[-1,-2,-3],[-10,-20,-30],[-100,-200,-300]])

In [48]:
a.mm(b)

tensor([[  -321.,   -642.,   -963.],
        [ -3210.,  -6420.,  -9630.],
        [-32100., -64200., -96300.]])

In [49]:
b = torch.FloatTensor([[-1],[-10],[100]])
b

tensor([[ -1.],
        [-10.],
        [100.]])

In [50]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

In [51]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

In [52]:
a = np.random.rand(3,3)
a

array([[0.39734974, 0.16918319, 0.61162   ],
       [0.22264209, 0.90553657, 0.12271461],
       [0.88504205, 0.63771276, 0.69284901]])

In [53]:
b = torch.from_numpy(a)
b

tensor([[0.3973, 0.1692, 0.6116],
        [0.2226, 0.9055, 0.1227],
        [0.8850, 0.6377, 0.6928]], dtype=torch.float64)

In [54]:
b -= b

In [55]:
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [56]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
a = torch.FloatTensor(2,3,4)
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [58]:
x = a.numpy()
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [59]:
x = torch.FloatTensor(1024,1024).uniform_()
x

tensor([[0.9616, 0.3831, 0.7958,  ..., 0.9376, 0.1332, 0.0909],
        [0.2380, 0.5058, 0.3507,  ..., 0.6496, 0.1994, 0.0400],
        [0.4381, 0.3425, 0.8176,  ..., 0.8471, 0.3558, 0.4425],
        ...,
        [0.4759, 0.3489, 0.5059,  ..., 0.1800, 0.8934, 0.7335],
        [0.9169, 0.8623, 0.0416,  ..., 0.1401, 0.3750, 0.3876],
        [0.7869, 0.8855, 0.8302,  ..., 0.9341, 0.5790, 0.9338]])

In [60]:
x.is_cuda

False

In [61]:
# x = x.cuda()

In [62]:
# ! nvcc -version